### ISSUE TITLE
⚡ Repository standardization

### ISSUE THREAD

**Issue by luxonauta** [shmink/dracula-peacock-extension#1]
Hi @shmink, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by shmink** [comment]
Hey @luxonauta 

Just made the changes as per the brief in [the latest commit](https://github.com/shmink/dracula-peacock-extension/commit/21b2d4e1d3759de5dff423a868478e97c7c35eda). Also a bit of a tidy up.
